spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shortener_url?serverTimezone=Asia/Seoul
    username: root
    password: 12345!
    hikari:
      maximum-pool-size: 40

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true